services:
  postgres:
    image: postgres:13
    container_name: featureflag-postgres
    environment:
      POSTGRES_DB: feature_flags
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Force password authentication
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d feature_flags"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:6
    container_name: featureflag-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local